PROGRAM stringreverse
	INTEGER :: LENGTH, I
	CHARACTER(80) :: STR
	CHARACTER :: TEMP

	PRINT *, "ENTER STRING" 
	READ *, STR
	PRINT *, STR
	LENGTH = LEN_TRIM(STR)
	DO I = 1, LENGTH/2
		TEMP = STR(I:I)
		STR(I:I) = STR(LENGTH + 1 - I:LENGTH + 1 - I)
		STR(LENGTH + 1 - I:LENGTH + 1 - I) = TEMP
	END DO
	PRINT *, STR 
END PROGRAM stringreverse
